import JSZip from 'jszip'
import { BRAND, MAX_HASHTAGS, MAX_SLIDES } from '../config/brand'
import { fontsReady } from '../render/fonts'
import { loadSlideImage } from '../render/images'
import { renderSlide } from '../render/slideRenderer'

export const IG_CAPTION_LIMIT = 2200

/** Renders one slide at full 1080x1350 and returns it as a PNG blob. */
export async function renderSlidePng(draft, index, settings) {
  await fontsReady
  const slide = draft.slides[index]
  let image = null
  try {
    image = await loadSlideImage(slide.image?.src)
  } catch {
    throw new Error(`Slide ${index + 1}: its image failed to load. Swap it and try again.`)
  }
  // OffscreenCanvas encodes immediately. HTMLCanvasElement.toBlob waits for idle time
  // in Chrome, which made exports crawl (~7s per slide) while the UI was updating.
  const canvas =
    typeof OffscreenCanvas === 'function'
      ? new OffscreenCanvas(BRAND.width, BRAND.height)
      : Object.assign(document.createElement('canvas'), { width: BRAND.width, height: BRAND.height })
  renderSlide(canvas, { slide, index, total: draft.slides.length, settings, image, style: draft.style })
  if (canvas.convertToBlob) return canvas.convertToBlob({ type: 'image/png' })
  return new Promise((resolve, reject) =>
    canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('Could not encode PNG'))), 'image/png'),
  )
}

// ------------------------------------------------------------------ text files

/**
 * Short credit line for images whose licence requires attribution (CC BY / BY-SA).
 * Public-domain and NASA images don't need it; they're listed in sources.txt instead.
 */
export function creditLine(draft) {
  const seen = new Set()
  const parts = []
  draft.slides.forEach((s, i) => {
    const img = s.image
    if (!img?.attributionRequired || seen.has(img.originalUrl || img.src)) return
    seen.add(img.originalUrl || img.src)
    parts.push(`${i + 1}) ${img.title} by ${img.credit}, ${img.licence}`)
  })
  return parts.length ? `Images: ${parts.join(' · ')} (via Wikimedia Commons)` : ''
}

/** The full text to paste into Instagram: caption, required credits, hashtags. */
export function composeCaption(draft) {
  return [draft.caption.trim(), creditLine(draft), draft.hashtags.join(' ')].filter(Boolean).join('\n\n')
}

function sourcesText(draft) {
  const lines = [
    draft.topic,
    `Exported ${new Date().toLocaleString()}${draft.model ? ` · text by ${draft.model}` : ''}`,
    '',
    'IMAGE SOURCES',
  ]
  draft.slides.forEach((s, i) => {
    const img = s.image || {}
    lines.push('', `Slide ${i + 1}: ${img.title || 'No image'}`)
    if (img.provider === 'placeholder') {
      lines.push('  Placeholder artwork generated by the app (no rights issues)')
      return
    }
    if (img.credit) lines.push(`  Credit:  ${img.credit}`)
    if (img.licence) lines.push(`  Licence: ${img.licence}${img.licenceUrl ? ` (${img.licenceUrl})` : ''}`)
    if (img.sourceUrl) lines.push(`  Source:  ${img.sourceUrl}`)
    if (img.attributionRequired) lines.push('  Attribution required: included in caption.txt')
  })
  if (draft.factCheck?.length) {
    lines.push('', 'CHECK BEFORE POSTING', ...draft.factCheck.map((f) => `- ${f}`))
  }
  return lines.join('\n') + '\n'
}

// ------------------------------------------------------------------ zip + download

export function exportIssues(draft) {
  const issues = []
  const placeholders = draft.slides.map((s, i) => (s.image?.provider === 'placeholder' ? i + 1 : null)).filter(Boolean)
  if (placeholders.length) issues.push(`Slide ${placeholders.join(', ')} still use placeholder images.`)
  const length = composeCaption(draft).length
  if (length > IG_CAPTION_LIMIT) issues.push(`Caption is ${length} characters (Instagram allows ${IG_CAPTION_LIMIT}).`)
  if (!draft.caption.trim()) issues.push('The caption is empty.')
  if (draft.slides.length > MAX_SLIDES) issues.push(`There are ${draft.slides.length} slides (Instagram allows ${MAX_SLIDES}).`)
  if (draft.hashtags.length > MAX_HASHTAGS) issues.push(`There are ${draft.hashtags.length} hashtags (Instagram allows ${MAX_HASHTAGS}).`)
  return issues
}

export function fileSlug(draft) {
  const date = new Date().toISOString().slice(0, 10)
  const slug = (draft.topic || 'post')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50)
  return `${date}-${slug || 'post'}`
}

/** Builds the zip: slide-01.png ... + caption.txt + sources.txt. */
export async function exportPostZip(draft, settings, onProgress = () => {}) {
  const zip = new JSZip()
  const folder = zip.folder(fileSlug(draft))
  // PNG encoding runs off the main thread, so encode every slide in parallel.
  let done = 0
  const total = draft.slides.length
  onProgress(`Rendering 0/${total}…`)
  const pngs = await Promise.all(
    draft.slides.map((_, i) =>
      renderSlidePng(draft, i, settings).then((blob) => {
        onProgress(`Rendering ${++done}/${total}…`)
        return blob
      }),
    ),
  )
  pngs.forEach((blob, i) => folder.file(`slide-${String(i + 1).padStart(2, '0')}.png`, blob))
  folder.file('caption.txt', composeCaption(draft) + '\n')
  folder.file('sources.txt', sourcesText(draft))
  onProgress('Zipping…')
  // PNGs are already compressed; STORE keeps zipping fast.
  const blob = await zip.generateAsync({ type: 'blob', compression: 'STORE' })
  downloadBlob(blob, `${fileSlug(draft)}.zip`)
}

export async function exportSinglePng(draft, index, settings) {
  const blob = await renderSlidePng(draft, index, settings)
  downloadBlob(blob, `${fileSlug(draft)}-slide-${String(index + 1).padStart(2, '0')}.png`)
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}
